<div class="row">
<?php echo $this->sidebar;?>
    <div class="col-sm-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Message info</h3>
            </div>
            <div class="panel-body">
                <?php 
				//echo "<pre>";print_r($this->messageinfo);exit;
				if($this->messageinfo) : 
					$messageinfo = $this->messageinfo;

					if($messageinfo['date']!=0)
					{
						$date = date("D, M dS Y",$messageinfo['date']);
					}
					else
					{
						$date = date("D, M dS Y");
					}
				?>

                <div class="form-horizontal">                                      
					<div class="form-group">
						<div class="width-100">
							<div class="agency_info">Sent By</div>
							<div class="agency_info"><?=$messageinfo['name']?></div>
							<div class="clear"></div>
							<div class="agency_info">Date</div>
							<div class="agency_info"><?=$date?></div>
							<div class="clear"></div>
							<div class="agency_info">Message</div>
							<div class="agency_info"><?=$messageinfo['message']?></div>
						</div>
					</div>
                </div>
                <?php endif; ?>
            </div>
        </div>    
    </div>
</div>    