<?php if(count($this->arrDataList) < 1) : ?>
    <p><?php echo $this->translate('no job posted yet');?></p>
<?php else: ?>    
    <?php foreach ( $this->arrDataList as $this->arrData ):?>
	<?php
	//here i am encoding jobid using encoding no one can't change id
	$job_id = base64_encode($this->arrData->id);	
	?>
    <div id="<?php echo $this->arrData->id;?>" class="panel panel-default">
        <div class="panel-heading">
            <p class="badge pull-right"><strong>Applied On: </strong> <?php echo date("D M, dS Y",strtotime($this->arrData->applied_date));?></p>			
        </div>
        <div class="panel-body">            
            <div class="form-horizontal">
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Title: </label>
                  <div class="col-lg-8"><p class="form-control-static"><?php echo wordwrap($this->escape($this->arrData->title), 90, "<br />\n",true);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Description: </label>
                  <div class="col-lg-8"><p class="form-control-static"><?php echo wordwrap($this->escape($this->arrData->description), 120, "<br />\n",true);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Job type: </label>
                  <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->jobType[$this->arrData->type])?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Estimate: </label>
                  <div class="col-lg-8"><p class="form-control-static"><?php echo ($this->arrData->type=="1")?"$".$this->escape($this->arrData->estimate):$this->escape($this->arrData->estimate)." Hours";?></p></div>
                </div>
            </div>
        </div>
    </div>     
    <?php endforeach;?>   
<?php endif; ?>
   
<?php echo $this->paginationControl ( $this->objPaginator, 'Sliding', 'paginator.phtml', array ('extraVar' => $this->pagingExtraVar ) ); ?>