<div class="row">
<?php echo $this->find_contractors;?>
    <div class="col-sm-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->contractors['type']?></h3>
            </div>
            <div class="panel-body">                
                <?php if($this->contractors['result']) : ?>
					<div id="profiles">
						<?php
						foreach($this->contractors['result'] as $contractor)
						{
							$url_link = $this->url(array('module'=>'agency','controller'=>'contract','action'=>'index'), null, true);							
						?>
							<div class="single_profile">
								<div class="profile_pic">
									<?php if($contractor['portrait']){?>
										<img class="img-thumbnail" src="<?=ASSETS_PATH.$contractor['portrait']?>" width="100">
									<?php }else{?>
										<img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH."portrait.png&w=100";?>" class="img-thumbnail">
									<?php } ?>
								</div>
								<div class="profile_body">
									
									<?php
									if($this->contractors['type']=="Contractor")
									{
									?>
										<div class="profile_name"><a href="<?=$url_link."/index/contractor_id/".$contractor['id']?>"><?=ucfirst($contractor['firstname']." ".$contractor['lastname'])?></a></div>
									<?php
									}
									else
									{
									?>
										<div class="profile_name"><?=ucfirst($contractor['firstname']." ".$contractor['lastname'])?></div>
									<?php
									}
									?>
									<div class="profile_title"><h4><?=$contractor['profile_title']?></h4></div>
									<?=$contractor['profile_desc']?>
								</div>
							</div>
						<?php
						}
						?>
					</div>
				<?php else:?>
					<div>
						No User Found
					</div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>