<div class="col-sm-2">
    <div class="list-group">      
      <a class="list-group-item active" href="<?php echo $this->url(array('module'=>'agency','controller'=>'index','action'=>'profile'), null, true);?>">My profile</a>          
    </div>
	<div class="list-group">      
      <a class="list-group-item active" href="<?php echo $this->url(array('module'=>'agency','controller'=>'agent','action'=>'message'), null, true);?>">Messages</a>          
    </div>
</div>