<div class="wedget">
	<form name="find_user" method="POST">
		<div class="form-group">
			<label class="control-label"><?php echo $this->translate('Find User');?></label>
			<div class=""><?php echo $this->value->type;?></div>
		</div>
		<div class="form-group">
			<label class="control-label"><?php echo $this->translate('Enter Name');?></label>
			<div class=""><?php echo $this->value->find;?></div>
		</div>
		<div class="form-group">		
			<div class=""><?php echo $this->value->submit;?></div>
		</div>
	</form>
</div>