<div class="row">
    <?php echo $this->sidebar;?>
    <div class="col-sm-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">My Profile</h3>
            </div>
            <div class="panel-body">
                <?php //echo '<pre>';print_r($this->profileData);echo '</pre>';?>
                <?php if( isset($this->profileData) ) : ?>                
                <div class="form-horizontal">                                      
                  <div class="form-group">
                    <label class="col-lg-2 control-label">&nbsp;</label>
                    <div class="col-lg-10">
                        <p class="form-control-static"> 
                            <a href="<?php echo $this->url(array('module'=>'agency','controller'=>'index','action'=>'editprofile'), null, true);?>" class="pull-right">Edit Profile</a> 
                        </p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Portrait</label>
                    <div class="col-lg-10">
                      <p class="form-control-static">
                          <?php if( $this->profileData['portrait']!="" && file_exists(ASSETS_ROOT_PATH.$this->profileData['portrait']) ) : ?>                          
                            <img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH.$this->profileData['portrait']."&w=100";?>" class="img-thumbnail">
                          <?php else : ?>
                            <img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH."portrait.png&w=100";?>" class="img-thumbnail">
                          <?php endif;?>
                      </p>
                    </div>
                  </div>                                        
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Email</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['email'];?></p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Username</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['username'];?></p>
                    </div>
                  </div>  
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Firstname</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['firstname'];?></p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Lastname</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['lastname'];?></p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Country</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo ucfirst(strtolower($this->profileData['country_name']));?></p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-2 control-label">City</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['city'];?></p>
                    </div>
                  </div>
				  <hr>
				  <div class="form-group">
                    <label class="col-lg-2 control-label">Profile Title</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['profile_title'];?></p>
                    </div>
                  </div>
				  <div class="form-group">
                    <label class="col-lg-2 control-label">Profile Desc</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['profile_desc'];?></p>
                    </div>
                  </div>
                                  <div class="form-group">
                    <label class="col-lg-2 control-label">Profile hourly rate</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['profile_hourly_rate'];?></p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-2 control-label">Last modified</label>
                    <div class="col-lg-10">
                      <p class="form-control-static"><?php echo $this->profileData['modified'];?></p>
                    </div>
                  </div>  
                    
                </div>
                <?php endif; ?>
                
                
            </div>
        </div>    
    </div>   
    
</div>    