<div class="row">                    
    <blockquote>
        <p><?php echo $this->translate('Change Password');?></p>
        <small>Provide new password to change Password</small>
    </blockquote>        
    <form class="form-horizontal" action="" method="POST" role="form">      
      <div class="form-group">
        <label for="inputEmail1" class="col-lg-2 control-label"><?php echo $this->translate('New Password');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->password;?></div>
      </div>
      <div class="form-group">
        <label for="inputEmail1" class="col-lg-2 control-label"><?php echo $this->translate('Retype Password');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->retypepassword;?></div>
      </div>  
        <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10"><?php echo $this->objForm->submit;?></div>
      </div>
    </form>                
</div>        