<div class="row">                    
    <blockquote>
        <p><?php echo $this->translate('Recover Forgot Password');?></p>
        <small>Recover Forgot Password</small>
    </blockquote>        
    <form class="form-horizontal" action="" method="POST" role="form">
      <div class="form-group">
        <label for="inputEmail1" class="col-lg-2 control-label"><?php echo $this->translate('Email');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->email;?></div>
      </div>                          
        <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10"><?php echo $this->objForm->submit;?></div>
      </div>
    </form>                
</div>        