<div class="row">        
    <div class="jumbotron">
        <h3>Welcome to Connectica</h3>    
        <p>
            <a class="btn btn-success btn-lg" href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'register','member'=>'employer'), null, true);?>">Post a job It's free</a>
                <a class="btn btn-info btn-lg" href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'register','member'=>'contractor'), null, true);?>">Want a job Signup now</a>
        </p>
        <p>Already have account? <a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'login'), null, true);?>">Sign In</a></p>
    </div>          
        
</div>            