<div class="col-sm-2">
    <div class="list-group">      
      <a class="list-group-item active" href="<?php echo $this->url(array('module'=>'contractor','controller'=>'index','action'=>'profile'), null, true);?>">Compose</a>
    </div>
    <div class="list-group">
      <a class="list-group-item active" href="<?php echo $this->url(array('module'=>'contractor','controller'=>'index','action'=>'profile'), null, true);?>">Inbox</a>
    </div>
	<div class="list-group">
      <a class="list-group-item " href="<?php echo $this->url(array('module'=>'contractor','controller'=>'agency','action'=>'message'), null, true);?>">Sent</a>
    </div>
</div>