<?php if(count($this->arrDataList) < 1) : ?>
    <p><?php echo $this->translate('no any contractor or agency found');?></p>
<?php else: ?>    
    <a class="btn btn-link" href="javascript:history.go(-1)"><< Back</a>
	<?php foreach ( $this->arrDataList as $this->arrData ):?>    
	<div id="<?php echo $this->arrData->id;?>" class="panel panel-default">
        <div class="panel-heading">                          
            <div class="form-horizontal">
            <div class="form-group">
                <label for="" class="col-lg-1 control-label">
                    <?php if( $this->arrData->portrait!="" && file_exists(ASSETS_ROOT_PATH.$this->arrData->portrait) ) : ?>                          
                      <img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH.$this->arrData->portrait."&w=100";?>" class="img-thumbnail">
                    <?php else : ?>
                      <img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH."portrait.png&w=100";?>" class="img-thumbnail">
                    <?php endif;?>
                </label>
                <div class="col-lg-4">
                    <p class="form-control-static"><strong>Name:</strong> <?php echo ($this->arrData->firstname);?> <?php echo ($this->arrData->lastname);?></p>
                    <p class="form-control-static"><strong>Email:</strong> <?php echo ($this->arrData->email);?></p>
                    <p class="form-control-static"><strong>Username:</strong> <?php echo ($this->arrData->username);?></p>                        
                </div>
                <div class="col-lg-7">
                    <span class="badge pull-right"><?php echo $this->userType[$this->arrData->type];?></span>            
                </div>
            </div>                
            </div>                        
        </div>        
        <div class="panel-footer">
            <?php if(empty($this->contractStatus)) : ?>
                <a href="<?php echo $this->url(array('module'=>'agency','controller'=>'contract','action'=>'add','contractor_id'=>$this->arrData->id,'job_id'=>$this->job_id), null, true);?>"><span class="badge">start contract</span></a>
            <?php else:  ?>
                <a href="javascript:void(0);"><span class="badge">contract already started</span></a>
            <?php endif; ?>
        </div>
    </div>     
    <?php endforeach;?>   
<?php endif; ?>
   
<?php echo $this->paginationControl ( $this->objPaginator, 'Sliding', 'paginator.phtml', array ('extraVar' => $this->pagingExtraVar ) ); ?>