<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head><title></title></head>
<body>
<div>
    <?php //_pr($this->contractData);?>       
    <p>contract is updated</p>    
    <p>contract title: <?php echo $this->contractData['title'];?></p>
    <p>contract description: <?php echo $this->contractData['description'];?></p>    
</div>
</body>
</html>