<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head><title></title></head>
<body>
<div>
    <?php //_pr($this->data);?>
    <p>You have posted new job</p>    
    <p>job title: <?php echo $this->data['title'];?></p>
    <p>job description: <?php echo $this->data['description'];?></p>
    <p>job estimate: <?php echo $this->data['estimate'];?></p>    
</div>
</body>
</html>