<?php if ($this->pageCount) : ?>    
	<ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li><a class='prev' href="<?= $this->url(array('page' => $this->previous)); ?>"> <? echo $this->translate('<<');?></a></li>
        <?php else: ?>
           <li><span class='prev' > <? echo $this->translate('<<');?></span></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != $this->current): ?>
            <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
          <?php else: ?>
            <li><span class="active"> <?php echo $page; ?></span></li>
          <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
          <li><a class="next" href="<?php echo $this->url(array('page' => $this->next)); ?>"> <?php echo $this->translate('>>');?></a></li>
        <?php else: ?>
           <li><span class="next"><?php echo $this->translate('>>');?> </span></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>