<div class="row jquery-ui">                
    <form class="form-horizontal" action="" method="POST" role="form">                  
      <div class="form-group">
        <label class="col-lg-2 control-label"><?php echo $this->translate('title');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->title;?></div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label"><?php echo $this->translate('description');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->description;?></div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label"><?php echo $this->translate('status');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->status;?></div>
      </div>  
      <div class="form-group">
        <label class="col-lg-2 control-label"><?php echo $this->translate('manual_allowed');?></label>
        <div class="col-lg-4"><?php echo $this->objForm->manual_allowed;?></div>
      </div>           
        
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10"><?php echo $this->objForm->submit;?></div>
      </div>
    </form>            
</div>