<!-- rateit jquery plugin -->
<?php $this->headLink()->offsetSetStylesheet(11 ,$this->baseUrl().'/css/rateit/rateit.css');?>
<?php $this->headScript()->offsetSetFile(11 ,$this->baseUrl().'/js/rateit/jquery.rateit.min.js');?>

<?php if(count($this->arrData) < 1) : ?>
    <p><?php echo $this->translate('no record found');?></p>
<?php else: ?>                    
    <div class="panel panel-<?php echo $this->jobStatusAlert[$this->arrData['contract_status']];?>">        
        <div class="panel-heading">
            <strong>Contract for : </strong> <?php echo $this->escape($this->arrData['contract_title']);?>
            <span class="badge pull-right"><?php echo $this->jobStatus[$this->arrData['contract_status']];?></span>
        </div>
        <div class="panel-body">            
            <div class="form-horizontal">
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Title: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['contract_title']);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Description: </label>
                  <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['contract_description']);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Status: </label>
                  <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->jobStatus[$this->arrData['contract_status']]);?></p></div>
                </div>                
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Started at: </label>
                  <div class="col-lg-8">
                      <p class="form-control-static">
                          <?php $date = new DateTime($this->arrData['contract_created']);?>
                          <?php echo $date->format('g:ia \o\n l jS F Y');?>
                      </p>
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Last changed at: </label>
                  <div class="col-lg-8">
                      <p class="form-control-static">
                          <?php $date = new DateTime($this->arrData['contract_modified']);?>
                          <?php echo $date->format('g:ia \o\n l jS F Y');?>                                                    
                      </p>
                  </div>
                </div>
            </div>
        </div>
        
        <div class="panel-heading">
            Job detail :
        </div>
        <div class="panel-body">            
            <div class="form-horizontal">
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">job title: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['job_title']);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">job description: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['job_description']);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">job type: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->jobType[$this->arrData['job_type']]);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">job estimate: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo ($this->arrData['job_type']=="1")?"$".$this->escape($this->arrData['job_estimate']):$this->escape($this->arrData['job_estimate'])." Hours";?></p></div>
                </div>                
            </div>
        </div>
        
        <div class="panel-heading">
            employer detail :
        </div>
        <div class="panel-body">            
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-lg-2 control-label">employer portrait</label>
                    <div class="col-lg-10">
                      <p class="form-control-static">
                          <?php if( $this->arrData['employer_portrait']!="" && file_exists(ASSETS_ROOT_PATH.$this->arrData['employer_portrait']) ) : ?>                          
                            <img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH.$this->arrData['employer_portrait']."&w=100";?>" class="img-thumbnail">
                          <?php else : ?>
                            <img src="<?php echo PHPTHUMB_PATH.ASSETS_PATH."portrait.png&w=100";?>" class="img-thumbnail">
                          <?php endif;?>
                      </p>
                    </div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">employer firstname: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['employer_firstname']);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">employer lastname: </label>
                    <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['employer_lastname']);?></p></div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">employer email: </label>
                        <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['employer_email']);?></p></div>
                </div>                
                <?php if($this->arrData['contractor_rating']!='' && $this->arrData['contractor_review']!='') : ?>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Employer rating to you: </label>
                    <div class="col-lg-8">                            
                        <div class="form-control-static rateit" data-rateit-value="<?php echo $this->escape($this->arrData['contractor_rating']);?>" data-rateit-ispreset="true" data-rateit-readonly="true"></div>                              
                    </div>
                </div>
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Employer review to you: </label>
                        <div class="col-lg-8"><p class="form-control-static"><?php echo $this->escape($this->arrData['contractor_review']);?></p></div>
                </div>
                <?php endif;?>
                
                <?php if($this->arrData['contract_status']=='4') : ?>
                <hr>
                
                <?php if(($this->arrData['employer_rating']!='') && ($this->arrData['employer_review']!='')) : ?>                
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Provide rating to Employer: </label>
                    <div class="col-lg-8">
                        <div class="form-control-static rateit" data-rateit-value="<?php echo $this->escape($this->arrData['employer_rating']);?>" data-rateit-ispreset="true" data-rateit-readonly="true"></div>                        
                    </div>                                                
                </div>                
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Provide review to Employer: </label>
                        <div class="col-lg-8">
                            <p class="form-control-static"><?php echo $this->arrData['employer_review'];?></p>
                        </div>
                </div>                
                <?php else: ?>
                <form method="post">
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Provide rating to Employer: </label>
                    <div class="col-lg-8">
                        <p class="form-control-static"><?php echo $this->objForm->employer_rating;?></p>
                        <div class="rateit" data-rateit-backingfld="#employer_rating"></div>
                    </div>                                                
                </div>                
                <div class="form-group">
                  <label for="inputEmail1" class="col-lg-2 control-label">Provide review to Employer: </label>
                        <div class="col-lg-8"><p class="form-control-static"><?php echo $this->objForm->employer_review;?></p></div>
                </div>
                <div class="form-group">
                    <label for="inputEmail1" class="col-lg-2 control-label">&nbsp;</label>
                        <div class="col-lg-8"><p class="form-control-static"><?php echo $this->objForm->submit;?></p></div>
                </div>
                </form>
                <?php endif;?>
                <?php endif;?>
                
                
                
                
            </div>
        </div>
        
    </div>            
<?php endif; ?>
